version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    image: portfolio-frontend
    restart: always
    expose:
      - 80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: portfolio-backend
    restart: always
    expose:
      - 5000

  nginx:
    build:
      context: ./nginx
    image: portfolio-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
