FROM node:18

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Install PM2 globally
RUN npm install -g pm2

# Copy the rest of the code
COPY . .

# Expose backend port
EXPOSE 5000

# Start app using PM2
CMD ["pm2-runtime", "ecosystem.config.js"]
